# Generated by Django 6.1.1 on 2026-09-21 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('answered_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='question_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='question_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('lobby', 'Lobby'), ('question', 'Question'), ('reveal', 'Reveal'), ('finished', 'Finished')], default='lobby', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['question', 'reveal']), _negated=True), models.Q(('question_ends_at__isnull', False), ('question_index__isnull', False)), _connector='OR'), name='games_game_live_has_question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quizzes.choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='games.participant'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quizzes.question'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('participant', 'question'), name='games_answer_one_per_question'),
        ),
    ]
